### ISSUE TITLE
Week6 - issues

### ISSUE THREAD

**Issue by Alicechung** [Alicechung/ML_finalPJT#2]
(O) 1. trade, unfair 라는 단어가 추가 

(O) 2. 연설을 한 연도 뿐만이 아니라 월/일 데이터도 있어야 동일 후보의 primary 선거 전후의 단어선택을 비교해볼 수 있음

(O)3. 그리고 파이썬에서 city 뿐만이 아니라 state 정보까지 구할 수 있는 방법/
city 자료로 state을 merge 하려고 했더니, 미국엔 하나의 city가 두개 이상의 state으로 나누어 지는 경우들이 종종 있어서 깨끗하게 1:1 merge가 안되는 경우가 발생  

        1) City 정보로 주 매칭 (dictionary 사용)
        2) geograpy 사용시 주까지 매칭되는 경우가 있으나 도시가 부정확한 경우도 발생
        3) Hardcode도 어느정도는 필요함
4. 3번 해결 후 rustbelt region (10개 주) 에 해당하는걸로 subset 만들어서 한번 더 Modelling
5. text type별로 클리닝

**Comment by Alicechung** [comment]
From Justin:

1. What are the set of speeches that you used?  (like how many per elected official)? 
2. I think the more relevant quantity that you'll want to use is the rate, rather than the number of words used (so divide by the length of the speech please) 
3. i'd also encourage you to consider the trade words and the extent to which they are protectionist.  For example, is hillary clinton criticizing NAFTA or defending it? Mexico is often used to discuss immigration, not just immigration.  China is also discussed as a geopolitical threat.  

4. I would think the easiest thing to do is to use a topic model to see if you can find a protectionist topic.  If that doesn't work you might try to hand code what makes a speech a protectionist topic. If neither of those work, perhaps expanding your words would be best.

**Comment by Alicechung** [comment]
PE2016 - STM with 10 topics

            [,1]           [,2]               [,3]                [,4]             [,5]                [,6]                     [,7]         
 [1,] "guilti"  "wisconsin"  "candidaci"    "louisiana" "politician" "washington"       "announc"    
 [2,] "nafta"   "lie"        "donor"        "hillari"   "mexico"     "african-american" "inner"      
 [3,] "mortgag" "invis"      "foreclosur"   "medic"     "nurs"       "senat"            "blitzer"    
 [4,] "rubio"   "perri"      "texa"         "maryland"  "omalley"    "mayor"            "conservat"  
 [5,] "huckabe" "russert"    "arkansa"      "schieffer" "mike"       "stephanopoulo"    "mccain"     
 [6,] "assad"   "isil"       "graham"       "capabl"    "peac"       "regim"            "normal"     
 [7,] "clinton" "children"   "centuri"      "donald"    "hard"       "confid"           "women"      
 [8,] "israel"  "imagin"     "jewish"       "cruz"      "aipac"      "pari"             "palestinian"
 [9,] "karen"   "rick"       "pennsylvania" "gentlemen" "someon"     "grandfath"        "ladi"       
[10,] "sander"  "billionair" "berni"        "greec"     "matthew"    "hay"              "daili"      
           [,8]            [,9]            [,10]       
 [1,] "depend"  "deserv"   "bureaucrat"
 [2,] "trump"   "fbi"      "rig"       
 [3,] "renew"   "servic"   "webb"      
 [4,] "lgbtq"   "baltimor" "explor"    
 [5,] "axelrod" "pakistan" "desk"      
 [6,] "iran"    "zone"     "forc"      
 [7,] "woman"   "ohio"     "global"    
 [8,] "missil"  "liberti"  "hama"      
 [9,] "folk"    "race"     "contrast"  
[10,] "cuomo"   "vermont"  "wealth"

**Comment by Alicechung** [comment]
1. rustbelt region (10개 주) 에 해당하는걸로 subset 만들어서 한번 더 Modelling

**Comment by Alicechung** [comment]
PE 2008 -STM

          V1      V2            V3           V4         V5          V6        V7      V8       V9          V10
1        dodd   harri stephanopoulo      resolut     caucus connecticut       mrs skeptic     sort          gun
2      edward   biden      lobbyist       corpor      escal  settlement    author compact     mill        moral
3     huckabe arkansa          mike      axelrod      cheer       straw      desk campbel     ladi    gentlemen
4  richardson  mexico       mexican      realism      qaeda       latin    urgent nuclear    rural      teacher
5    giuliani   mayor          york         nato       rudi        citi interpret excerpt laughter   commission
6       invis mortgag       clinton         nurs foreclosur        ohio   hillari blitzer   colleg       autism
7    thompson    fred          upon     tennesse standpoint    principl     awhil  notion  charact        littl
8      romney    mitt           ann massachusett     embryo       jihad   marriag    evil michigan          dad
9      street oreilli         obama      chicago     afford      relief      wall   black   barack middle-class
10    hanniti  wallac        mccain          sen      drill       palin     obama  couric  succeed      arizona

**Comment by Alicechung** [comment]
PE2012-STM

         V1       V2           V3     V4           V5        V6      V7          V8       V9      V10
1      cain   herman      pursuit   dodd        alter   atlanta    hill      vision    happi    olymp
2  huntsman    trust    gentlemen    jon relationship      ladi  abroad        fuel  presenc monopoli
3       ron     paul     monetari   gold         bail     print liberti       money     king   reserv
4    colleg  michell         auto member          bet everybodi audienc         got outstand     weve
5     assad     arab    democraci  truth        regim minnesota   libya     protest  subsidi    syria
6     karen santorum pennsylvania someon         race  missouri  counti        town     rick michigan
7      adam waterloo     bachmann treati       michel     settl   choos     marriag   republ   repeal
8  gingrich     newt      gasolin   quot      speaker    gallon pipelin       laugh   report   format
9     perri   explor         texa broken       employ  downgrad     gov environment      epa  greater
10     mitt     flag       romney    usa       number       boy    ryan         kid   school      hes

**Comment by minjukim1220** [comment]
1. 전체주 (40개주) vs. rustbelt 지역 (10개주) 비교 분석이랑 더불어서
 2. swing state + rustbelt (4개주) vs. non-swing state + rustbelt (6개주) 비교해보는것도 좋을것 같아. 

페이퍼 읽다가 영감이 떠올랐는데, swing state + rustbelt 지역은 non-swing state + rustbelt 지역보다 credit-claiming (돈 유치)에 더 적극적일것 같아. 후자는 credit-claiming보다는 capital 이 적게 들어가는 position-taking (중국의 무역관행이 "unfair"함을 강조)가 상대적으로 더 팽배할것 같고.

**Comment by minjukim1220** [comment]
**실직 후 재교육 프로그램 및 지원 정책: Trade Adjustment Assistance (TAA), Social
Security Disability Insurance (SSDI), Social Security Retirement Insurance

***예상 Credit Claiming Key Word: fund, dollar, million, billion, trade adjustment, adjustment, income assistance, income, assistance, social security, disability, disability insurance, retirement, retirement insurance, welfare, revitalize, retrain, employ

다만 다소 부정적인 단어들 (disability, retirement, assistance)이 대통령 선거 연설에서 빈번하게 등장할 지는 미지수임.
